<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
<!-- Base -->
  <xacro:macro name="base_link" params="length radius">
    <link name="base_footprint">
    </link>
    <link name="base_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${length}" radius="${radius}"/>
        </geometry>
        <material name="white">
          <color rgba="1.0 1.0 1.0 0.5"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${length}" radius="${radius}"/>
        </geometry>
        <material name="white">
          <color rgba="1.0 1.0 1.0 0.5"/>
        </material>
      </collision>
    </link>
    <joint name="base_link_joint" type="fixed">
      <parent link="base_footprint"/>
      <child link="base_link"/>
      <origin xyz="0 0 ${length/2.0}" rpy="0 0 0"/>
    </joint>
  </xacro:macro>
</robot>